### ISSUE TITLE
只要涉及到Model就直接罢工

### ISSUE THREAD

**Issue by DavidTai780** [Pinatra/Pinatra#6]
我是个新手，最近刚开始。在过程中全程跟着Pinatra的指南走，但是到了那个Model只要一访问就出现HTTP 500错误。 请问这个可能是什么问题呢？谢谢

**Comment by olatiao** [comment]
= = Model的代码贴上来看看

**Comment by DavidTai780** [comment]
Article.php

<?php

namespace Model;

class Article extends \Pinatra\Model\Model {
	protected $table = 'articles';
	$articles = Article::all(); 
	foreach ($articles as $article) {
		echo $article->title;
	}
}

**Comment by johnlui** [comment]
HTTP 500 之后有报错信息吗，贴一下就知道了

**Comment by DavidTai780** [comment]
2019/03/06 12:28:24 [error] 2396#15052: *1 FastCGI sent in stderr: "PHP Fatal error:  Uncaught Error: Undefined constant 'Model\Article' in C:\Users\User\Desktop\nginx\webs\Pinatra\Controllers\ArticleController.php:11
Stack trace:
#0 [internal function]: Controllers\ArticleController->article()
#1 C:\Users\User\Desktop\nginx\webs\Pinatra\src\Routing\Router.php(128): call_user_func_array(Array, Array)
#2 C:\Users\User\Desktop\nginx\webs\Pinatra\src\FirePinatra.php(38): Pinatra\Routing\Router::dispatch('\\Pinatra\\View\\V...')
#3 [internal function]: dispatch()
#4 {main}
  thrown in C:\Users\User\Desktop\nginx\webs\Pinatra\Controllers\ArticleController.php on line 11" while reading response header from upstream, client: 127.0.0.1, server: pinatra.php, request: "GET /article HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "pinatra.php"

这个是nginx错误日志

**Comment by johnlui** [comment]
Undefined constant 'Model\Article'

自动加载问题，这个文件没有加载到，这个类没有识别，目测 comsoper.json 没有配置

**Comment by DavidTai780** [comment]
"autoload": {
        "psr-4": {
            "Pinatra\\": "src/",
			"Controllers\\": "Controllers/",
			"Model\\": "Models/"
        },


这里配置了呀

**Comment by DavidTai780** [comment]
非常谢谢回答，问题现已找到问题所在，是namespace之前有空格。由于之前的namespace是在<?php的下一行出现空位所以php无法执行

```
**<?php
namespace Model;**
class Article extends \Pinatra\Model\Model {
	protected $table = 'articles';
	//public $primaryKey = 'id';
	//$articles = Article::all(); // 此处得到的 $articles 是一个对象集合，可以在后面加上 '->toArray()' 变成多维数组。
	//foreach ($articles as $article) {
	//	echo $article->title;
	//}
}
```


换成


```
<?phpnamespace Model;
class Article extends \Pinatra\Model\Model {
	protected $table = 'articles';
	//public $primaryKey = 'id';
	//$articles = Article::all(); // 此处得到的 $articles 是一个对象集合，可以在后面加上 '->toArray()' 变成多维数组。
	//foreach ($articles as $article) {
	//	echo $article->title;
	//}
}
```

**Comment by johnlui** [comment]
这也行。。。我都是空一行。。。

**Comment by olatiao** [comment]
2333333333
看不懂

**Comment by DavidTai780** [comment]
网络上搜出来的
