### ISSUE TITLE
同样涉及到model就直接502

### ISSUE THREAD

**Issue by olatiao** [Pinatra/Pinatra#8]
**Controllers**
```
<?php
namespace Controllers;
use Pinatra\Model\DB;

class HomeController
{
  public function home()
  {
	return \Model\Article::first()->id;
  }
}
```
**Models**
```
<?php
namespace Model;

class Article extends \Pinatra\Model\Model
{
	  protected $table = 'article';
}
```
php-fpm报错
```
[11-Apr-2019 07:22:28 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Illuminate\Database\Query\Builder::find(), 0 passed in /var/www/p/controllers/HomeController.php on line 9 and at least 1 expected in /var/www/p/vendor/illuminate/database/Query/Builder.php:2081
Stack trace:
#0 /var/www/p/controllers/HomeController.php(9): Illuminate\Database\Query\Builder->find()
#1 [internal function]: Controllers\HomeController->home()
#2 /var/www/p/vendor/pinatra/framework/src/Routing/Router.php(128): call_user_func_array(Array, Array)
#3 /var/www/p/vendor/pinatra/framework/src/FirePinatra.php(38): Pinatra\Routing\Router::dispatch('\\Pinatra\\View\\V...')
#4 [internal function]: dispatch()
#5 {main}
  thrown in /var/www/p/vendor/illuminate/database/Query/Builder.php on line 2081
```

**Comment by johnlui** [comment]
PHP 版本多少？可能是没达到 Eloquent 的要求

**Comment by johnlui** [comment]
我查了下，最新的 Eloquent 要求 PHP7.2：https://github.com/illuminate/database/blob/master/composer.json

看来我需要指定一下版本了

**Comment by olatiao** [comment]
哈哈哈  我是php7.2的

**Comment by johnlui** [comment]
我在 MAC 上用 7.3 的 PHP -S 试了试没问题，要不你也用 PHP -S 试试？

**Comment by olatiao** [comment]
运行php -s 一直卡着是什么鬼

**Comment by olatiao** [comment]
运行php -S的话出来一堆php的命令help

**Comment by johnlui** [comment]
php -S 0.0.0.0:8000

**Comment by olatiao** [comment]
- - 我用的是nginx呀

**Comment by johnlui** [comment]
> * * 我用的是nginx呀

这不是在找问题嘛。。。

**Comment by olatiao** [comment]
好的,我以为跟nginx是一样的,抱歉哈,我试试

**Comment by olatiao** [comment]
```
Could not open input file: 0.0.0.0:8000
```

提示这个

**Comment by johnlui** [comment]
目测你的 -s 是小写的

**Comment by olatiao** [comment]
是的,哈哈哈哈  我换成大写

**Comment by olatiao** [comment]
http://47.96.92.16:8000/
这里启动没问题,.
再去访问的话就有数据出来了
- - 这是为啥呀

**Comment by johnlui** [comment]
那就是你的环境的问题，php-fpm 的问题

**Comment by olatiao** [comment]
那麻烦问下我应该从哪儿着手查呢

**Comment by johnlui** [comment]
不知道，要不你更新到 4.3 。。。

**Comment by johnlui** [comment]
你可以换用 Apache，记得用这个装 PHP：https://webtatic.com/

**Comment by olatiao** [comment]
我擦~~
现在用nginx又可以了
奇了怪了

**Comment by johnlui** [comment]
可能是你没重启 php-fpm

**Comment by olatiao** [comment]
(⊙o⊙)哦
这倒也是个思路,
换句话说安装配置好项目后最好重启下php-fpm吗
- - 另外突然发现另外一个问题就是为啥var_dump好使但是dump不好使
